import React, { useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import FileUpload from "../components/file-upload.component";

export default function Home() {
    const [newUserInfo, setNewUserInfo] = useState({
        profileImages: []
    })

    const updateUploadedFiles = files =>
        setNewUserInfo({ ...newUserInfo, profileImages: files})

    const handleSubmit = e => {
        event.preventDefault();
        //some logic
    }

    return (
        <div className={styles.container}>
          <Head>
            <title>Document Converter</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
              <form onSubmit={handleSubmit}>
                  <FileUpload
                    accept=".jpg, .png, .jpeg"
                    label="Profile Image(s)"
                    multiple
                    updateFilesCb={updateUploadedFiles}
                  />
                  <button type="submit">Create New User</button>
              </form>
          </main>
        </div>
  )
}
